### ISSUE TITLE
Outdated contact information

### ISSUE THREAD

**Issue by kamichal** [aurzenligl/prophy#14]
I need to discuss a implementation of new feature in prophy with you, but the only contact I find in the whole repo is hosted at nokia.com.
Please update it in git and github config, setup.py, documentation, authors file and anywhere else.

**Comment by aurzenligl** [comment]
Hello! I just made an update:
https://github.com/aurzenligl/prophy/commit/ec317adacaebac30621c93adcdec5f27403f070c
Let's discuss via github/mail.
